=== isaac84/xfire/xfire-aegis/src/schema/mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://xfire.codehaus.org/aegis/1.0"
  xmlns:tns="http://xfire.codehaus.org/aegis/1.0"
  elementFormDefault="unqualified" 
  attributeFormDefault="unqualified" >

  <element name="mappings">
    <complexType>
      <sequence>
        <element name="mapping" minOccurs="0" maxOccurs="unbounded" type="tns:mappingType" />
      </sequence>
    </complexType>
  </element>

  <complexType name="mappingType">
    <sequence>
      <element minOccurs="0" maxOccurs="unbounded" ref="tns:property" />
    </sequence>
    <attribute name="uri" type="string"/>
    <attribute name="name" type="string"/>
  </complexType>

  <element name="property">
    <complexType>
      <attributeGroup ref="tns:mappedType"/>
      <anyAttribute namespace='##other' processContents='lax'/>
    </complexType>
  </element>
  
  <element name="return-type">
    <complexType>
      <attributeGroup ref="tns:mappedType"/>
      <anyAttribute namespace='##other' processContents='lax'/>
    </complexType>
  </element>
  
  <element name="parameter">
    <complexType>
      <attribute name="index" type="int"/>
      <attribute name="class" type="string"/>
      <attributeGroup ref="tns:mappedType"/>
      <anyAttribute namespace='##other' processContents='lax'/>
    </complexType>
  </element>

  <element name="component">
    <complexType>
      <attribute name="class" type="string"/>
      <attributeGroup ref="tns:mappedType"/>
      <anyAttribute namespace='##other' processContents='lax'/>
    </complexType>
  </element>
  
  <attributeGroup name="mappedType">
    <attribute name="name" type="string" />
    <attribute name="type" type="string" />
    <attribute name="typeName" type="string" />
    <attribute name="mappedName" type="string" />
    <attribute name="nillable" type="boolean" />
    <attribute name="ignore" type="boolean" />
    <attribute name="componentType" type="string" />
    <attribute name="keyType" type="string" />
    <attribute name="minOccurs" type="int"/>
    <attribute name="style">
      <simpleType>
        <restriction base="string">
          <enumeration value="attribute"/>
          <enumeration value="element"/>
        </restriction>
      </simpleType>
    </attribute>
    <anyAttribute namespace='##other' processContents='lax'/>
  </attributeGroup> 

</schema>

=== isaac84/xfire/xfire-aegis/src/test/org/codehaus/xfire/aegis/type/basic/MyBean.aegis.xml
<mappings xmlns:bean="urn:xfire:bean"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
   xsi:noNamespaceSchemaLocation="http://xfire.codehaus.org/schemas/1.0/mapping.xsd">
  
  <mapping uri="urn:xfire:bean">
    <property name="prop1" mappedName="Prop1"/>
    <property name="prop2" mappedName="Prop2" style="attribute"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean2">
    <property name="prop1" mappedName="Prop1"/>
    <property name="prop2" mappedName="Prop2"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean3">
    <property name="prop1" mappedName="Prop1"/>
    <property name="prop2" mappedName="Prop2"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean4">
    <property name="prop2" style="attribute"/>
  </mapping>

  <mapping uri="urn:xfire:bean5">
    <property name="prop1" ignore="true"/>
    <property name="prop2" ignore="true"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean-nillable">
    <property name="prop1" nillable="false"/>
    <property name="prop2"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean-minoccurs">
    <property name="prop1" minOccurs="1"/>
    <property name="prop2"/>
  </mapping>
  
  <mapping uri="urn:xfire:bean-extensible">
  </mapping>
  
  <mapping uri="urn:xfire:bean-extensibleoff" extensibleElements="false" extensibleAttributes="false">
  </mapping>
  
  <mapping uri="urn:xfire:custom-type">
    <property name="prop1" type="org.codehaus.xfire.aegis.type.basic.MyStringType"/>
  </mapping>
  
  <mapping uri="urn:xfire:custom-ns" xmlns:t="urn:Bean" name="t:Bean"/>
</mappings>
